<a href="https://colab.research.google.com/github/Rakeshboin/Dap-python/blob/main/Assi_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Analyze the provided financial data for a retail chain with three stores (A, B, and C) and three product categories (Groceries, Clothing, and Electronics). Prepare a 3x3 revenue matrix and a 3x3 expenses matrix. Calculate the net revenue matrix. Adjust the revenue matrix for an 8% inflation factor and transpose the adjusted matrix. Interpret the results to identify the best performing store and category combination and the most profitable store overall.

## Revenue matrix preparation

### Subtask:
Create a 3x3 matrix representing monthly revenue for each store and product category.


**Reasoning**:
Create a list of lists with the revenue data and convert it to a NumPy array as requested by the subtask.



In [1]:
import numpy as np

# Revenue data (Store A, B, C) x (Groceries, Clothing, Electronics)
revenue_data = [
    [5000, 3000, 2000],  # Store A
    [6000, 4500, 3500],  # Store B
    [5500, 4000, 3000]   # Store C
]

# Convert the list of lists to a NumPy array
revenue_matrix = np.array(revenue_data)

print("Revenue Matrix:")
print(revenue_matrix)

Revenue Matrix:
[[5000 3000 2000]
 [6000 4500 3500]
 [5500 4000 3000]]


## Expenses matrix preparation

### Subtask:
Create a 3x3 matrix representing monthly operational expenses for each store and product category.


**Reasoning**:
Create a list of lists for the expenses data, convert it to a NumPy array, and then print the array.



In [2]:
# Expenses data (Store A, B, C) x (Groceries, Clothing, Electronics)
expenses_data = [
    [2000, 1500, 1000],  # Store A
    [2500, 2000, 1500],  # Store B
    [2200, 1800, 1200]   # Store C
]

# Convert the list of lists to a NumPy array
expenses_matrix = np.array(expenses_data)

print("\nExpenses Matrix:")
print(expenses_matrix)


Expenses Matrix:
[[2000 1500 1000]
 [2500 2000 1500]
 [2200 1800 1200]]


## Calculate net revenue

### Subtask:
Subtract the expenses matrix from the revenue matrix to find the net revenue for each category in each store.


**Reasoning**:
Subtract the expenses matrix from the revenue matrix to calculate the net revenue matrix and then print the result.



In [3]:
# Subtract the expenses matrix from the revenue matrix to find the net revenue
net_revenue_matrix = revenue_matrix - expenses_matrix

# Print the net revenue matrix
print("\nNet Revenue Matrix:")
print(net_revenue_matrix)


Net Revenue Matrix:
[[3000 1500 1000]
 [3500 2500 2000]
 [3300 2200 1800]]


## Adjust for inflation

### Subtask:
Multiply the revenue matrix by an inflation factor of 1.08 to simulate future pricing adjustments.


**Reasoning**:
Multiply the revenue matrix by the inflation factor to calculate the adjusted revenue matrix and then print it.



In [4]:
# Multiply the revenue matrix by the inflation factor
inflation_factor = 1.08
adjusted_revenue_matrix = revenue_matrix * inflation_factor

# Print the adjusted revenue matrix
print("\nAdjusted Revenue Matrix (with 8% inflation):")
print(adjusted_revenue_matrix)


Adjusted Revenue Matrix (with 8% inflation):
[[5400. 3240. 2160.]
 [6480. 4860. 3780.]
 [5940. 4320. 3240.]]


## Transpose the adjusted matrix

### Subtask:
Transpose the inflation-adjusted revenue matrix to view revenue per product category across stores.


**Reasoning**:
Transpose the adjusted revenue matrix and print it with a descriptive label.



In [5]:
# Transpose the adjusted_revenue_matrix
transposed_adjusted_revenue_matrix = adjusted_revenue_matrix.T

# Print the transposed adjusted revenue matrix
print("\nTransposed Adjusted Revenue Matrix (Revenue per Category across Stores):")
print(transposed_adjusted_revenue_matrix)


Transposed Adjusted Revenue Matrix (Revenue per Category across Stores):
[[5400. 6480. 5940.]
 [3240. 4860. 4320.]
 [2160. 3780. 3240.]]


## Interpret the results

### Subtask:
Analyze the transposed matrix to identify the best performing store and category combination and determine the most profitable store overall.


**Reasoning**:
Analyze the transposed adjusted revenue matrix to find the best performing store and category combination and the most profitable store overall.



In [6]:
# Find the highest value in the transposed adjusted revenue matrix
max_revenue = np.max(transposed_adjusted_revenue_matrix)

# Find the index of the highest value
max_index = np.argmax(transposed_adjusted_revenue_matrix)

# Determine the row and column corresponding to the highest value
# Rows represent categories (0: Groceries, 1: Clothing, 2: Electronics)
# Columns represent stores (0: A, 1: B, 2: C)
row_index, col_index = np.unravel_index(max_index, transposed_adjusted_revenue_matrix.shape)

# Map indices to category and store names
categories = ['Groceries', 'Clothing', 'Electronics']
stores = ['A', 'B', 'C']

best_category = categories[row_index]
best_store = stores[col_index]

print(f"\nBest performing store and category combination (inflation-adjusted revenue):")
print(f"Store: {best_store}, Category: {best_category}, Revenue: {max_revenue:.2f}")

# Calculate total inflation-adjusted revenue for each store
total_revenue_per_store = np.sum(transposed_adjusted_revenue_matrix, axis=0)

# Find the index of the store with the highest total revenue
most_profitable_store_index = np.argmax(total_revenue_per_store)

# Determine the most profitable store
most_profitable_store = stores[most_profitable_store_index]

print("\nTotal inflation-adjusted revenue per store:")
for i in range(len(stores)):
    print(f"Store {stores[i]}: {total_revenue_per_store[i]:.2f}")

print(f"\nMost profitable store overall (based on total inflation-adjusted revenue): {most_profitable_store}")


Best performing store and category combination (inflation-adjusted revenue):
Store: B, Category: Groceries, Revenue: 6480.00

Total inflation-adjusted revenue per store:
Store A: 10800.00
Store B: 15120.00
Store C: 13500.00

Most profitable store overall (based on total inflation-adjusted revenue): B


## Summary:

### Q&A

*   **What is the best performing store and category combination based on inflation-adjusted revenue?**
    The best performing combination is Store B in the Groceries category, with an inflation-adjusted revenue of \$6480.00.
*   **Which is the most profitable store overall, based on total inflation-adjusted revenue?**
    The most profitable store overall is Store B.

### Data Analysis Key Findings

*   The initial revenue matrix was:
    ```
    [[5000 3000 2000]
     [6000 4500 3500]
     [5500 4000 3000]]
    ```
*   The initial expenses matrix was:
    ```
    [[2000 1500 1000]
     [2500 2000 1500]
     [2200 1800 1200]]
    ```
*   The net revenue matrix (Revenue - Expenses) was calculated as:
    ```
    [[3000 1500 1000]
     [3500 2500 2000]
     [3300 2200 1800]]
    ```
*   The revenue matrix adjusted for an 8% inflation factor was:
    ```
    [[5400. 3240. 2160.]
     [6480. 4860. 3780.]
     [5940. 4320. 3240.]]
    ```
*   The transposed adjusted revenue matrix, showing revenue per category across stores, was:
    ```
    [[5400. 6480. 5940.]
     [3240. 4860. 4320.]
     [2160. 3780. 3240.]]
    ```
*   The total inflation-adjusted revenue per store was: Store A: \$10800.00, Store B: \$15120.00, Store C: \$13500.00.

### Insights or Next Steps

*   Store B demonstrates strong performance in the Groceries category and is the most profitable store overall based on current and inflation-adjusted revenue.
*   Further analysis could involve examining the net revenue matrix to understand the profitability of each category within each store and identifying areas for cost optimization.
